# Pakolliset parametrit:
# - tietokanta: Tietokannan nimi
# - tietokannan_peruskayttaja: Tietokannan peruskäyttäjän nimi
#
# Valinnaiset parametrit:
# - tietokannan_peruskayttajan_salasana: Arvotaan, jos ei määritetty
---
- name: Lisää tietokannan peruskäyttäjä
  postgresql_user: name={{ tietokannan_peruskayttaja }}
  register: lisaa_peruskayttaja

- name: Aseta tietokannan peruskäyttäjän salasana
  postgresql_user: name={{ tietokannan_peruskayttaja }} password={{ tietokannan_peruskayttajan_salasana|default(lookup('password', inventory_dir + '/salasanat/tietokannan_peruskayttaja')) }}
  when: (tietokannan_peruskayttajan_salasana is defined) or lisaa_peruskayttaja|changed

- name: Anna tietokannan peruskäyttäjälle oikeudet tietokantaan
  command: psql -c 'GRANT CONNECT ON DATABASE {{ tietokanta }} TO {{ tietokannan_peruskayttaja }}'

- name: Anna tietokannan peruskäyttäjälle oikeudet kaikkiin tietokannan tauluihin
  command: psql -c 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {{ tietokannan_peruskayttaja }}' {{ tietokanta }}

- name: Anna tietokannan peruskäyttäjälle oikeudet kaikkiin tietokannan sekvensseihin
  command: psql -c 'GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO {{ tietokannan_peruskayttaja }}' {{ tietokanta }}
