---
- name: Tarkista, että ympäristöön saa ladata dumpin
  assert: that="'{{ salli_dumpin_lataus|default('no') }}'=='yes'"

- name: Kopioi dumppi palvelimelle
  copy: src="{{ dumppi }}" dest=/tmp/oph_db_dump.db owner=postgres mode=600

- name: Tee pgpass-tiedosto
  template: src=pgpass.j2 dest=/tmp/oph_db_dump.pgpass owner=postgres mode=600

- name: Poista palvelun oma skeema
  command: psql -d {{ tietokanta }} -c 'drop schema if exists {{ skeema }} cascade;'
  when: skeema is defined

- name: Tyhjennä public-skeema
  command: psql -d {{ tietokanta }} -c 'drop schema public cascade; create schema public; grant all on schema public to public; grant all on schema public to postgres;'

- name: Tee tietokannan pääkäyttäjästä superuser dumpin lataamisen ajaksi
  command: psql -d {{ tietokanta }} -c 'alter user {{ tietokannan_paakayttaja }} with superuser;'

- name: Lataa dumppi tietokantaan
  shell: PGPASSFILE=/tmp/oph_db_dump.pgpass pg_restore --no-acl --no-owner -h {{ tietokantapalvelimen_yksityinen_nimi|default(groups['oph_db'][0]) }} -U {{ tietokannan_paakayttaja }} -d {{ tietokanta }} /tmp/oph_db_dump.db

- name: Poista tietokannan pääkäyttäjän superuser-status
  command: psql -d {{ tietokanta }} -c 'alter user {{ tietokannan_paakayttaja }} with nosuperuser;'

- name: Poista pgpass-tiedosto
  file: dest=/tmp/oph_db_dump.pgpass state=absent

- name: Poista dumppi palvelimelta
  file: dest=/tmp/oph_db_dump.db state=absent
