---
- include: konfiguroi_tietokanta.yml

- name: Julkaise paikallisesti käännetty versio OPH:n palvelusta
  hosts: oph_palvelu
  sudo: yes
  gather_facts: no
  roles:
    - oph_palvelu
  vars:
    build: dev
