insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '38/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Audiovisuaalisen viestinnän perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Audiovisuaalisen viestinnän perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '38/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '39/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Autoalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Autoalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '39/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '40/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Elintarvikealan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Elintarvikealan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '40/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '41/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Hammastekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Hammastekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '41/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '42/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Hevostalouden perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Hevostalouden perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '42/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '43/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Hiusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Hiusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '43/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '44/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Hotelli-, ravintola- ja catering-alan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Hotelli-, ravintola- ja catering-alan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '44/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '45/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kaivosalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kaivosalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '45/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '46/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kalatalouden perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kalatalouden perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '46/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '47/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kauneudenhoitoalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kauneudenhoitoalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '47/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '48/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kello- ja mikromekaniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kello- ja mikromekaniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '48/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '49/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kiinteistöpalvelujen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kiinteistöpalvelujen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '49/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '50/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kone- ja metallialan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kone- ja metallialan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '50/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '51/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kotityö- ja puhdistuspalvelujen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kotityö- ja puhdistuspalvelujen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '51/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '52/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Kuvallisen ilmaisun perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Kuvallisen ilmaisun perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '52/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '53/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Käsi- ja taideteollisuusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Käsi- ja taideteollisuusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '53/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '55/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Laboratorioalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Laboratorioalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '55/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '56/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Lapsi- ja perhetyön perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Lapsi- ja perhetyön perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '56/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '57/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Lennonjohdon perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Lennonjohdon perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '57/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '58/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Lentokoneasennuksen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Lentokoneasennuksen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '58/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '59/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Liiketalouden perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Liiketalouden perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '59/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '60/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Liikunnanohjauksen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Liikunnanohjauksen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '60/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '61/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Logistiikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Logistiikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '61/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '62/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Luonto- ja ympäristöalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Luonto- ja ympäristöalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '62/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '54/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Lääkealan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Lääkealan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '54/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '63/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Maanmittausalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Maanmittausalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '63/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '64/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Maatalousalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Maatalousalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '64/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '65/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Matkailualan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Matkailualan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '65/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '66/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Merenkulkualan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Merenkulkualan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '66/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '67/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Metsäalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Metsäalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '67/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '1/011/2010' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Muovi- ja kumitekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Muovi- ja kumitekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '1/011/2010' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '69/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Musiikkialan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Musiikkialan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '69/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '70/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Nuoriso- ja vapaa-ajan ohjauksen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Nuoriso- ja vapaa-ajan ohjauksen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '70/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '71/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Painoviestinnän perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Painoviestinnän perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '71/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '72/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Pintakäsittelyalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Pintakäsittelyalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '72/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '73/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Prosessiteollisuuden perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Prosessiteollisuuden perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '73/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '74/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Puualan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Puualan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '74/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '75/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Puutarhatalouden perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Puutarhatalouden perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '75/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '76/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Rakennusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Rakennusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '76/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '78/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Sirkusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Sirkusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '78/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '79/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Sosiaali- ja terveysalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Sosiaali- ja terveysalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '79/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '77/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Sähkö- ja automaatiotekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Sähkö- ja automaatiotekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '77/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '81/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Talotekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Talotekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '81/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '82/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Tanssialan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Tanssialan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '82/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '80/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Teknisen suunnittelun perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Teknisen suunnittelun perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '80/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '83/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Tekstiili- ja vaatetusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Tekstiili- ja vaatetusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '83/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '84/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Tieto- ja tietoliikennetekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Tieto- ja tietoliikennetekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '84/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '85/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Tieto- ja viestintätekniikan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Tieto- ja viestintätekniikan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '85/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '86/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Turvallisuusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Turvallisuusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '86/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '87/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Veneenrakennuksen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Veneenrakennuksen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '87/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '88/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Verhoilu- ja sisustusalan perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Verhoilu- ja sisustusalan perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '88/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;

insert into tutkintoversio (tutkintotunnus, versio, peruste, hyvaksytty, voimassa_alkupvm, koodistoversio) select nt.tutkintotunnus, tv.versio + 1 as versio, '89/011/2014' as peruste, true as hyvaksytty, '2015-08-01'::date as voimassa_alkupvm, 1 as koodistoversio from nayttotutkinto nt join tutkintoversio tv on tv.tutkintoversio_id = nt.uusin_versio_id where nt.nimi_fi = 'Viittomakielisen ohjauksen perustutkinto';
update tutkintoversio set voimassa_loppupvm = '2015-07-31'::date from nayttotutkinto nt where nt.uusin_versio_id = tutkintoversio.tutkintoversio_id and nt.nimi_fi = 'Viittomakielisen ohjauksen perustutkinto';
with versiot as (update nayttotutkinto set uusin_versio_id = tv.tutkintoversio_id from nayttotutkinto nt2 join tutkintoversio tv on tv.tutkintotunnus = nt2.tutkintotunnus where nt2.tutkintotunnus = nayttotutkinto.tutkintotunnus and tv.peruste = '89/011/2014' returning nayttotutkinto.uusin_versio_id as uusi, nt2.uusin_versio_id as vanha)  update sopimus_ja_tutkinto set tutkintoversio = versiot.uusi from jarjestamissopimus, versiot where jarjestamissopimus.voimassa and jarjestamissopimus.jarjestamissopimusid = sopimus_ja_tutkinto.jarjestamissopimusid and versiot.vanha = sopimus_ja_tutkinto.tutkintoversio;
